# Generated by Django 5.2.8 on 2026-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedipaddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='ips',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedipaddress',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Blocked at'),
        ),
        migrations.AlterField(
            model_name='blockedipaddress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blockedipaddress',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
